### ISSUE TITLE
.track should use `this.events` to retrieve matching events

### ISSUE THREAD

**Issue by ndhoule** [segment-integrations/analytics.js-integration-kenshoo#1]
[Affected LOC](https://github.com/segment-integrations/analytics.js-integration-kenshoo/blob/0cb189335a1c034de278adb09a18c7211959883c/lib/index.js#L60)

Should instead use the new array-handling `events()` functionality introduced in https://github.com/segmentio/analytics.js-integration/pull/45; as written currently it's case-sensitive so it's more restrictive than it should be.

**Comment by hankim813** [comment]
added to jira https://segment.atlassian.net/browse/INT-182
